/**
 * @file index.ts
 * @description 种子数据模块：初始化系统预置数据，包括用户、文章、分类、标签、评论、通知、收藏等
 */
import { v4 as uuidv4 } from 'uuid';
import type { JsonFileStore } from '../store/JsonFileStore.js';

/** 生成 UUID v4 唯一标识（占位，保留以备扩展动态种子数据） */
const _id = (): string => uuidv4();

/** 预定义用户 ID 映射（固定字符串便于前后端关联） */
const USER_IDS = {
  alex: 'user-alex-chen',
  sarah: 'user-sarah-miller',
  david: 'user-david-park',
  emily: 'user-emily-watson',
  michael: 'user-michael-brown',
  lisa: 'user-lisa-zhang',
};

/** 预定义文章 ID 映射（固定字符串便于前后端关联） */
const ARTICLE_IDS = {
  rsc: 'article-rsc-2024',
  color: 'article-color-psychology',
  graphql: 'article-graphql-resilient',
  ts5: 'article-typescript-5',
  cssGrid: 'article-css-grid-flexbox',
  microservices: 'article-microservices-comm',
  ai: 'article-ai-powered-dev',
  rust: 'article-rust-web-dev',
  edge: 'article-edge-computing',
  accessibility: 'article-accessibility-first',
  microFe: 'article-micro-frontends',
  websockets: 'article-websockets-realtime',
  designSystem: 'article-design-systems-scale',
  codeReview: 'article-code-review',
  burnout: 'article-mindful-coding',
};

/**
 * 初始化种子数据
 * @description 向各集合注入预置数据（仅在集合为空时生效），用于演示与开发环境
 * @param store JSON 文件存储实例
 * @returns {Promise<void>} 所有集合种子写入完成后 resolve
 */
export async function seedData(store: JsonFileStore): Promise<void> {
  // ---- 用户（4 名种子账号，密码哈希对应明文 "password"） ----
  await store.seed('users', [
    {
      id: USER_IDS.alex,
      email: 'alex.chen@example.com',
      // SHA-256 哈希值，对应明文 "password"
      password: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      firstName: 'Alex',
      lastName: 'Chen',
      username: 'alexchen',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
      coverImage:
        'https://images.unsplash.com/photo-1517134191118-9d595e4c8c2b?w=1200&h=400&fit=crop',
      bio: 'Senior Frontend Engineer passionate about React and modern web development. Sharing my learnings and experiences in the tech industry.',
      location: 'San Francisco, CA',
      website: 'https://alexchen.dev',
      joined: 'March 2021',
      role: 'Senior Frontend Engineer',
      company: 'TechCorp',
      /** 是否官方认证用户（true=已认证 false=未认证） */
      verified: true,
      tags: ['React', 'TypeScript', 'Next.js', 'Frontend', 'Engineering'],
      social: { twitter: '@alexchen', github: 'alexchen', linkedin: 'alexchen' },
      stats: { articles: 48, followers: '12.5k', following: 234, likes: '45.2k', views: '1.2M' },
      createdAt: '2021-03-15T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
    {
      id: USER_IDS.sarah,
      email: 'sarah.miller@example.com',
      password: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      firstName: 'Sarah',
      lastName: 'Miller',
      username: 'sarahmiller',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      coverImage: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&h=400&fit=crop',
      bio: 'Product Designer with a background in psychology and visual arts. Creating meaningful digital experiences.',
      location: 'New York, NY',
      website: 'https://sarahmiller.design',
      joined: 'June 2020',
      role: 'Product Designer',
      company: 'DesignStudio',
      verified: true,
      tags: ['Design', 'UI/UX', 'Figma', 'Product Design'],
      social: { twitter: '@sarahmiller', github: 'sarahmiller', linkedin: 'sarahmiller' },
      stats: { articles: 32, followers: '8.9k', following: 156, likes: '28.4k', views: '890k' },
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
    {
      id: USER_IDS.david,
      email: 'david.park@example.com',
      password: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      firstName: 'David',
      lastName: 'Park',
      username: 'davidpark',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      coverImage: '',
      bio: 'Backend Engineer specializing in API design and distributed systems.',
      location: 'Seattle, WA',
      website: '',
      joined: 'January 2022',
      role: 'Backend Engineer',
      company: 'CloudScale',
      verified: false,
      tags: ['Architecture', 'GraphQL', 'Node.js', 'Backend'],
      social: { twitter: '@davidpark', github: 'davidpark', linkedin: 'davidpark' },
      stats: { articles: 15, followers: '1.8k', following: 89, likes: '8.2k', views: '320k' },
      createdAt: '2022-01-10T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
    {
      id: USER_IDS.emily,
      email: 'emily.watson@example.com',
      password: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      firstName: 'Emily',
      lastName: 'Watson',
      username: 'emilywatson',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
      coverImage: '',
      bio: 'Community Manager building bridges between writers and readers worldwide.',
      location: 'London, UK',
      website: '',
      joined: 'September 2021',
      role: 'Community Manager',
      company: 'DevCommunity',
      verified: true,
      tags: ['Community', 'Writing', 'Tutorials'],
      social: { twitter: '@emilywatson', github: 'emilywatson', linkedin: 'emilywatson' },
      stats: { articles: 22, followers: '4.5k', following: 312, likes: '15.6k', views: '560k' },
      createdAt: '2021-09-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
    },
  ]);

  // ---- 文章（含已发布、草稿、归档多种状态） ----
  await store.seed('articles', [
    {
      id: ARTICLE_IDS.rsc,
      title: 'Mastering React Server Components in 2024',
      excerpt:
        'A deep dive into how Server Components change the paradigm of building React applications, improving performance and developer experience.',
      image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=600&fit=crop',
      tag: 'Engineering',
      tagClass: 'tag-engineering',
      readTime: '8 min read',
      date: 'Nov 12, 2023',
      likes: 342,
      comments: 56,
      content:
        '<p>React Server Components represent a paradigm shift in how we build React applications...</p><h2>What Are Server Components?</h2><p>Server Components are React components that execute only on the server.</p><h2>Benefits</h2><ul><li>Zero Bundle Size</li><li>Direct Backend Access</li><li>Improved Performance</li></ul>',
      views: 45200,
      /** 文章状态（published=已发布 draft=草稿 archived=已归档） */
      status: 'published',
      /** 可见性（public=公开 private=私有） */
      visibility: 'public',
      /** 是否精选推荐（true=精选 false=否） */
      featured: true,
      categoryId: 'engineering',
      tags: ['engineering', 'react', 'server-components'],
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        bio: 'Senior Frontend Engineer',
      },
    },
    {
      id: ARTICLE_IDS.color,
      title: 'The Psychology of Colors in Digital Products',
      excerpt:
        'Understanding how different hues impact user behavior, emotional response, and brand perception in modern interface design.',
      image: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1200&h=600&fit=crop',
      tag: 'Design',
      tagClass: 'tag-design',
      readTime: '6 min read',
      date: 'Nov 08, 2023',
      likes: 218,
      comments: 24,
      content:
        "<p>Color is more than just a visual element—it's a powerful communication tool...</p><h2>How Colors Affect User Behavior</h2><p>Different colors trigger different psychological responses.</p>",
      views: 32100,
      status: 'published',
      visibility: 'public',
      featured: false,
      categoryId: 'design',
      tags: ['design', 'psychology', 'color-theory'],
      author: {
        name: 'Sarah Miller',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
        bio: 'Product Designer',
      },
    },
    {
      id: ARTICLE_IDS.graphql,
      title: 'Building Resilient APIs with GraphQL',
      excerpt:
        'Best practices for designing, implementing, and securing GraphQL endpoints for scalable frontend applications.',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&h=600&fit=crop',
      tag: 'Architecture',
      tagClass: 'tag-architecture',
      readTime: '10 min read',
      date: 'Oct 30, 2023',
      likes: 189,
      comments: 42,
      content:
        '<p>GraphQL has revolutionized how we think about API design...</p><h2>Schema Design Best Practices</h2><p>A well-designed schema is the foundation of a good GraphQL API.</p>',
      views: 28500,
      status: 'published',
      visibility: 'public',
      featured: true,
      categoryId: 'architecture',
      tags: ['architecture', 'graphql', 'api-design'],
      author: {
        name: 'David Park',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
        bio: 'Backend Engineer',
      },
    },
    {
      id: ARTICLE_IDS.ts5,
      title: "TypeScript 5.0: What's New and Exciting",
      excerpt:
        'Exploring the latest features in TypeScript 5.0 including decorators and performance improvements.',
      image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=250&fit=crop',
      tag: 'Engineering',
      tagClass: 'tag-engineering',
      readTime: '7 min read',
      date: 'Oct 25, 2023',
      likes: 156,
      comments: 31,
      content: '<p>TypeScript 5.0 brings exciting new features...</p>',
      views: 8200,
      status: 'published',
      visibility: 'public',
      featured: false,
      categoryId: 'engineering',
      tags: ['engineering', 'typescript'],
      author: {
        name: 'Emily Watson',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
        bio: 'Community Manager',
      },
    },
    {
      id: ARTICLE_IDS.cssGrid,
      title: 'CSS Grid vs Flexbox: When to Use Which',
      excerpt:
        'A comprehensive comparison of CSS Grid and Flexbox with practical examples and decision guidelines.',
      image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=400&h=250&fit=crop',
      tag: 'Frontend',
      tagClass: 'tag-frontend',
      readTime: '5 min read',
      date: 'Oct 20, 2023',
      likes: 423,
      comments: 67,
      content: '<p>CSS Grid and Flexbox are two powerful layout systems...</p>',
      views: 18900,
      status: 'published',
      visibility: 'public',
      featured: true,
      categoryId: 'frontend',
      tags: ['frontend', 'css', 'layout'],
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        bio: 'Senior Frontend Engineer',
      },
    },
    {
      id: ARTICLE_IDS.microservices,
      title: 'Microservices Communication Patterns',
      excerpt:
        'Understanding synchronous vs asynchronous communication, message queues, and service discovery in distributed systems.',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
      tag: 'Architecture',
      tagClass: 'tag-architecture',
      readTime: '12 min read',
      date: 'Oct 15, 2023',
      likes: 278,
      comments: 45,
      content: '<p>Microservices need to communicate with each other...</p>',
      views: 3100,
      status: 'published',
      visibility: 'public',
      featured: false,
      categoryId: 'architecture',
      tags: ['architecture', 'microservices'],
      author: {
        name: 'David Park',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
        bio: 'Backend Engineer',
      },
    },
    {
      id: ARTICLE_IDS.ai,
      title: 'AI-Powered Development: The Next Frontier',
      excerpt:
        'How AI assistants are transforming the way we write, review, and deploy code in 2024.',
      image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop',
      tag: 'Engineering',
      tagClass: 'tag-engineering',
      readTime: '12 min read',
      date: 'Dec 10, 2023',
      likes: 1024,
      comments: 156,
      content: '<p>AI is transforming software development...</p>',
      views: 68000,
      status: 'published',
      visibility: 'public',
      featured: true,
      categoryId: 'engineering',
      tags: ['engineering', 'ai', 'ml'],
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        bio: 'Senior Frontend Engineer',
      },
    },
    {
      id: ARTICLE_IDS.rust,
      title: 'Rust for Web Developers: A Gentle Introduction',
      excerpt: 'Why Rust is gaining popularity among web developers and how to get started.',
      image: 'https://images.unsplash.com/photo-1623479322729-28b25c16b011?w=400&h=250&fit=crop',
      tag: 'Tutorials',
      tagClass: 'tag-tutorials',
      readTime: '15 min read',
      date: 'Dec 08, 2023',
      likes: 876,
      comments: 98,
      content: '<p>Rust is gaining popularity...</p>',
      views: 52000,
      status: 'published',
      visibility: 'public',
      featured: false,
      categoryId: 'tutorials',
      tags: ['tutorials', 'rust'],
      author: {
        name: 'David Park',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
        bio: 'Backend Engineer',
      },
    },
    {
      id: ARTICLE_IDS.edge,
      title: 'The Rise of Edge Computing',
      excerpt:
        'Understanding how edge computing is reshaping application architecture and user experience.',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
      tag: 'Architecture',
      tagClass: 'tag-architecture',
      readTime: '10 min read',
      date: 'Dec 06, 2023',
      likes: 654,
      comments: 72,
      content: '<p>Edge computing is reshaping how we build applications...</p>',
      views: 38000,
      status: 'published',
      visibility: 'public',
      featured: false,
      categoryId: 'architecture',
      tags: ['architecture', 'edge-computing'],
      author: {
        name: 'David Park',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
        bio: 'Backend Engineer',
      },
    },
    {
      id: ARTICLE_IDS.accessibility,
      title: 'Accessibility-First Design Patterns',
      excerpt:
        'Building inclusive digital experiences with practical accessibility patterns and techniques.',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop',
      tag: 'Design',
      tagClass: 'tag-design',
      readTime: '8 min read',
      date: 'Dec 04, 2023',
      likes: 543,
      comments: 61,
      content: '<p>Accessibility should be a first-class concern...</p>',
      views: 29000,
      status: 'published',
      visibility: 'public',
      featured: false,
      categoryId: 'design',
      tags: ['design', 'accessibility'],
      author: {
        name: 'Sarah Miller',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
        bio: 'Product Designer',
      },
    },
    {
      id: ARTICLE_IDS.microFe,
      title: 'Micro-Frontends in Production',
      excerpt:
        'Real-world lessons learned from implementing micro-frontend architectures at scale.',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=250&fit=crop',
      tag: 'Frontend',
      tagClass: 'tag-frontend',
      readTime: '11 min read',
      date: 'Dec 02, 2023',
      likes: 432,
      comments: 54,
      content: '<p>Micro-frontends allow teams to work independently...</p>',
      views: 24000,
      status: 'published',
      visibility: 'public',
      featured: false,
      categoryId: 'frontend',
      tags: ['frontend', 'micro-frontends'],
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        bio: 'Senior Frontend Engineer',
      },
    },
    // 草稿状态文章
    {
      id: 'article-draft-design-system',
      title: 'Building a Design System from Scratch',
      excerpt:
        'Lessons learned from creating a scalable design system for enterprise applications...',
      image: '',
      tag: 'Design',
      tagClass: 'tag-design',
      readTime: '6 min read',
      date: '',
      likes: 0,
      comments: 0,
      content: '<p>Draft content...</p>',
      views: 0,
      status: 'draft',
      visibility: 'private',
      featured: false,
      categoryId: 'design',
      tags: ['design', 'design-system'],
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        bio: 'Senior Frontend Engineer',
      },
    },
    {
      id: 'article-draft-web-workers',
      title: 'Understanding Web Workers in JavaScript',
      excerpt:
        'How to leverage Web Workers for heavy computation without blocking the main thread...',
      image: '',
      tag: 'Engineering',
      tagClass: 'tag-engineering',
      readTime: '10 min read',
      date: '',
      likes: 0,
      comments: 0,
      content: '<p>Draft content...</p>',
      views: 0,
      status: 'draft',
      visibility: 'private',
      featured: false,
      categoryId: 'engineering',
      tags: ['engineering', 'web-workers'],
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        bio: 'Senior Frontend Engineer',
      },
    },
    // 归档状态文章
    {
      id: 'article-archived-edge',
      title: 'The Rise of Edge Computing',
      excerpt: 'Why edge computing matters and how it changes application architecture...',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
      tag: 'Architecture',
      tagClass: 'tag-architecture',
      readTime: '8 min read',
      date: 'Sep 15, 2023',
      likes: 89,
      comments: 12,
      content: '<p>Archived content...</p>',
      views: 3100,
      status: 'archived',
      visibility: 'public',
      featured: false,
      categoryId: 'architecture',
      tags: ['architecture', 'edge-computing'],
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        bio: 'Senior Frontend Engineer',
      },
    },
  ]);

  // ---- 文章分类（6 个一级分类） ----
  await store.seed('categories', [
    {
      id: 'engineering',
      name: 'Engineering',
      description:
        'Deep dives into software engineering, architecture patterns, and best practices.',
      icon: 'Code',
      color: 'tag-engineering',
      textColor: 'tag-engineering-text',
      articleCount: 24,
      followers: '1.2k',
      longDescription:
        'Explore the world of software engineering with in-depth articles covering system design, coding patterns, algorithms, and industry best practices.',
      bgGradient: 'from-blue-500/10 to-blue-600/5',
      trending: 8,
      weeklyGrowth: '+12%',
      topTags: ['React', 'TypeScript', 'Node.js', 'System Design', 'Algorithms', 'Testing'],
    },
    {
      id: 'design',
      name: 'Design',
      description: 'Exploring UI/UX principles, design systems, and creative workflows.',
      icon: 'Palette',
      color: 'tag-design',
      textColor: 'tag-design-text',
      articleCount: 18,
      followers: '890',
      longDescription: 'Dive into the art and science of digital design.',
      bgGradient: 'from-pink-500/10 to-pink-600/5',
      trending: 5,
      weeklyGrowth: '+8%',
      topTags: ['UI/UX', 'Figma', 'Design Systems', 'Color Theory', 'Typography', 'Prototyping'],
    },
    {
      id: 'architecture',
      name: 'Architecture',
      description: 'System design, microservices, and scalable infrastructure patterns.',
      icon: 'Layers',
      color: 'tag-architecture',
      textColor: 'tag-architecture-text',
      articleCount: 15,
      followers: '650',
      longDescription:
        'Master the principles of building scalable, reliable, and maintainable systems.',
      bgGradient: 'from-amber-500/10 to-amber-600/5',
      trending: 6,
      weeklyGrowth: '+15%',
      topTags: ['Microservices', 'Cloud', 'Kubernetes', 'AWS', 'Docker', 'CI/CD'],
    },
    {
      id: 'lifestyle',
      name: 'Lifestyle',
      description: 'Work-life balance, productivity tips, and personal growth stories.',
      icon: 'Coffee',
      color: 'tag-lifestyle',
      textColor: 'tag-lifestyle-text',
      articleCount: 12,
      followers: '420',
      longDescription: 'Discover insights on maintaining a healthy work-life balance.',
      bgGradient: 'from-emerald-500/10 to-emerald-600/5',
      trending: 3,
      weeklyGrowth: '+5%',
      topTags: ['Productivity', 'Remote Work', 'Mental Health', 'Career Growth', 'Books', 'Habits'],
    },
    {
      id: 'tutorials',
      name: 'Tutorials',
      description: 'Step-by-step guides and hands-on learning resources.',
      icon: 'BookOpen',
      color: 'tag-tutorials',
      textColor: 'tag-tutorials-text',
      articleCount: 32,
      followers: '2.1k',
      longDescription: 'Hands-on tutorials and step-by-step guides.',
      bgGradient: 'from-indigo-500/10 to-indigo-600/5',
      trending: 12,
      weeklyGrowth: '+20%',
      topTags: [
        'Getting Started',
        'Projects',
        'Tips & Tricks',
        'Best Practices',
        'Code Along',
        'Challenges',
      ],
    },
    {
      id: 'frontend',
      name: 'Frontend',
      description: 'React, Vue, CSS, and modern frontend development techniques.',
      icon: 'Zap',
      color: 'tag-frontend',
      textColor: 'tag-frontend-text',
      articleCount: 28,
      followers: '1.8k',
      longDescription: 'Stay up-to-date with the latest in frontend development.',
      bgGradient: 'from-violet-500/10 to-violet-600/5',
      trending: 10,
      weeklyGrowth: '+18%',
      topTags: ['React', 'Vue', 'CSS', 'Performance', 'Accessibility', 'Build Tools'],
    },
  ]);

  // ---- 标签库（12 个热门技术标签） ----
  await store.seed('tags', [
    {
      name: 'React',
      description: 'A JavaScript library for building user interfaces',
      articles: 156,
      followers: '45.2k',
      /** 是否为热门趋势标签（true=热门 false=普通） */
      trending: true,
      weeklyGrowth: '+23%',
      related: ['Next.js', 'TypeScript', 'JavaScript', 'Frontend', 'Hooks'],
    },
    {
      name: 'TypeScript',
      description: 'TypeScript is a typed superset of JavaScript',
      articles: 89,
      followers: '32.1k',
      trending: true,
      weeklyGrowth: '+18%',
      related: ['JavaScript', 'React', 'Node.js', 'Frontend', 'Backend'],
    },
    {
      name: 'Next.js',
      description: 'The React Framework for the Web',
      articles: 124,
      followers: '38.9k',
      trending: true,
      weeklyGrowth: '+31%',
      related: ['React', 'TypeScript', 'Vercel', 'SSR', 'Frontend'],
    },
    {
      name: 'Design',
      description: 'UI/UX design principles and best practices',
      articles: 203,
      followers: '52.4k',
      trending: false,
      weeklyGrowth: '+8%',
      related: ['Figma', 'UI/UX', 'CSS', 'Typography', 'Color Theory'],
    },
    {
      name: 'GraphQL',
      description: 'A query language for APIs',
      articles: 67,
      followers: '18.5k',
      trending: true,
      weeklyGrowth: '+14%',
      related: ['API', 'Backend', 'Node.js', 'React', 'Apollo'],
    },
    {
      name: 'CSS',
      description: 'Cascading Style Sheets for web styling',
      articles: 145,
      followers: '28.7k',
      trending: false,
      weeklyGrowth: '+6%',
      related: ['Frontend', 'Design', 'Animation', 'Layout', 'Tailwind'],
    },
    {
      name: 'Node.js',
      description: 'JavaScript runtime built on V8',
      articles: 98,
      followers: '35.2k',
      trending: false,
      weeklyGrowth: '+9%',
      related: ['Backend', 'Express', 'JavaScript', 'API', 'NPM'],
    },
    {
      name: 'Docker',
      description: 'Containerization platform',
      articles: 56,
      followers: '22.1k',
      trending: false,
      weeklyGrowth: '+7%',
      related: ['DevOps', 'Kubernetes', 'Cloud', 'CI/CD', 'Microservices'],
    },
    {
      name: 'AWS',
      description: 'Amazon Web Services',
      articles: 78,
      followers: '29.8k',
      trending: true,
      weeklyGrowth: '+11%',
      related: ['Cloud', 'Serverless', 'DevOps', 'Infrastructure', 'Lambda'],
    },
    {
      name: 'Git',
      description: 'Distributed version control system',
      articles: 45,
      followers: '15.3k',
      trending: false,
      weeklyGrowth: '+4%',
      related: ['GitHub', 'Version Control', 'CI/CD', 'Collaboration', 'DevOps'],
    },
    {
      name: 'Testing',
      description: 'Software testing methodologies',
      articles: 62,
      followers: '19.7k',
      trending: false,
      weeklyGrowth: '+5%',
      related: ['Jest', 'Cypress', 'Unit Testing', 'E2E', 'TDD'],
    },
    {
      name: 'Performance',
      description: 'Web performance optimization',
      articles: 54,
      followers: '21.4k',
      trending: true,
      weeklyGrowth: '+16%',
      related: ['Core Web Vitals', 'Lighthouse', 'Optimization', 'Caching', 'CDN'],
    },
  ]);

  // ---- 评论（4 条种子评论，含 1 条回复形成父子关系） ----
  await store.seed('comments', [
    {
      id: 'comment-1',
      articleId: ARTICLE_IDS.rsc,
      userId: USER_IDS.sarah,
      userName: 'Sarah Miller',
      userAvatar:
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      content: 'Great article! This really helped me understand Server Components better.',
      createdAt: '2023-11-13T10:30:00.000Z',
      likes: 12,
    },
    {
      id: 'comment-2',
      articleId: ARTICLE_IDS.rsc,
      userId: USER_IDS.david,
      userName: 'David Park',
      userAvatar:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      content:
        'Would love to see a follow-up on combining Server Components with client-side state management.',
      createdAt: '2023-11-13T14:20:00.000Z',
      likes: 8,
      /** 父评论 ID，用于构建回复树 */
      parentId: 'comment-1',
    },
    {
      id: 'comment-3',
      articleId: ARTICLE_IDS.color,
      userId: USER_IDS.emily,
      userName: 'Emily Watson',
      userAvatar:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      content: 'The section on accessibility considerations was really insightful!',
      createdAt: '2023-11-09T08:15:00.000Z',
      likes: 5,
    },
    {
      id: 'comment-4',
      articleId: ARTICLE_IDS.graphql,
      userId: USER_IDS.alex,
      userName: 'Alex Chen',
      userAvatar:
        'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
      content: 'The DataLoader pattern is a game-changer for N+1 queries. Great coverage!',
      createdAt: '2023-10-31T16:45:00.000Z',
      likes: 15,
    },
  ]);

  // ---- 通知（6 条给 Alex 用户的系统通知） ----
  await store.seed('notifications', [
    {
      id: 'notif-1',
      userId: USER_IDS.alex,
      /** 通知类型（like=点赞 comment=评论 follow=关注 article=文章 mention=提及） */
      type: 'like',
      title: 'Sarah Miller liked your article',
      message: '"Mastering React Server Components in 2024"',
      link: '/article/article-rsc-2024',
      /** 是否已读（true=已读 false=未读） */
      read: false,
      createdAt: '2023-12-10T08:30:00.000Z',
      fromUser: {
        name: 'Sarah Miller',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      },
    },
    {
      id: 'notif-2',
      userId: USER_IDS.alex,
      type: 'comment',
      title: 'New comment on your article',
      message:
        'David Park: Great article! This really helped me understand Server Components better.',
      link: '/article/article-rsc-2024',
      read: false,
      createdAt: '2023-12-10T07:00:00.000Z',
      fromUser: {
        name: 'David Park',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      },
    },
    {
      id: 'notif-3',
      userId: USER_IDS.alex,
      type: 'follow',
      title: 'Emily Watson started following you',
      message: 'You have a new follower',
      link: '/author/user-emily-watson',
      read: false,
      createdAt: '2023-12-09T22:00:00.000Z',
      fromUser: {
        name: 'Emily Watson',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      },
    },
    {
      id: 'notif-4',
      userId: USER_IDS.alex,
      type: 'article',
      title: 'Your article was featured',
      message: '"Building Resilient APIs with GraphQL" is now trending in Architecture',
      link: '/article/article-graphql-resilient',
      read: true,
      createdAt: '2023-12-09T18:00:00.000Z',
    },
    {
      id: 'notif-5',
      userId: USER_IDS.alex,
      type: 'like',
      title: 'Michael Brown and 12 others liked your comment',
      message: "On 'CSS Grid vs Flexbox: When to Use Which'",
      link: '/article/article-css-grid-flexbox',
      read: true,
      createdAt: '2023-12-08T12:00:00.000Z',
      fromUser: {
        name: 'Michael Brown',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
      },
    },
    {
      id: 'notif-6',
      userId: USER_IDS.alex,
      type: 'mention',
      title: 'Lisa Zhang mentioned you in a comment',
      message: '@alexchen What do you think about using Server Components with...',
      link: '/article/article-rsc-2024',
      read: true,
      createdAt: '2023-12-07T09:00:00.000Z',
      fromUser: {
        name: 'Lisa Zhang',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
      },
    },
  ]);

  // ---- 收藏与阅读列表（5 条 Alex 用户的收藏/稍后阅读） ----
  await store.seed('favorites', [
    {
      id: 'fav-1',
      userId: USER_IDS.alex,
      articleId: ARTICLE_IDS.cssGrid,
      /** 收藏类型（favorite=收藏 reading-list=稍后阅读） */
      type: 'favorite',
      createdAt: '2023-12-01T10:00:00.000Z',
    },
    {
      id: 'fav-2',
      userId: USER_IDS.alex,
      articleId: ARTICLE_IDS.burnout,
      type: 'favorite',
      createdAt: '2023-11-20T14:00:00.000Z',
    },
    {
      id: 'fav-3',
      userId: USER_IDS.alex,
      articleId: ARTICLE_IDS.websockets,
      type: 'reading-list',
      createdAt: '2023-12-05T09:00:00.000Z',
    },
    {
      id: 'fav-4',
      userId: USER_IDS.alex,
      articleId: ARTICLE_IDS.designSystem,
      type: 'reading-list',
      createdAt: '2023-12-01T11:00:00.000Z',
    },
    {
      id: 'fav-5',
      userId: USER_IDS.alex,
      articleId: ARTICLE_IDS.codeReview,
      type: 'reading-list',
      createdAt: '2023-11-28T16:00:00.000Z',
    },
  ]);

  // ---- 热门文章榜单（Trending 页面用） ----
  await store.seed('trending_articles', [
    {
      id: ARTICLE_IDS.ai,
      title: 'AI-Powered Development: The Next Frontier',
      excerpt:
        'How AI assistants are transforming the way we write, review, and deploy code in 2024.',
      image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop',
      tag: 'Engineering',
      tagClass: 'tag-engineering',
      readTime: '12 min read',
      date: 'Dec 10, 2023',
      likes: 1024,
      comments: 156,
    },
    {
      id: ARTICLE_IDS.rust,
      title: 'Rust for Web Developers: A Gentle Introduction',
      excerpt: 'Why Rust is gaining popularity among web developers and how to get started.',
      image: 'https://images.unsplash.com/photo-1623479322729-28b25c16b011?w=400&h=250&fit=crop',
      tag: 'Tutorials',
      tagClass: 'tag-tutorials',
      readTime: '15 min read',
      date: 'Dec 08, 2023',
      likes: 876,
      comments: 98,
    },
    {
      id: ARTICLE_IDS.edge,
      title: 'The Rise of Edge Computing',
      excerpt:
        'Understanding how edge computing is reshaping application architecture and user experience.',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
      tag: 'Architecture',
      tagClass: 'tag-architecture',
      readTime: '10 min read',
      date: 'Dec 06, 2023',
      likes: 654,
      comments: 72,
    },
    {
      id: ARTICLE_IDS.accessibility,
      title: 'Accessibility-First Design Patterns',
      excerpt:
        'Building inclusive digital experiences with practical accessibility patterns and techniques.',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop',
      tag: 'Design',
      tagClass: 'tag-design',
      readTime: '8 min read',
      date: 'Dec 04, 2023',
      likes: 543,
      comments: 61,
    },
    {
      id: ARTICLE_IDS.microFe,
      title: 'Micro-Frontends in Production',
      excerpt:
        'Real-world lessons learned from implementing micro-frontend architectures at scale.',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=250&fit=crop',
      tag: 'Frontend',
      tagClass: 'tag-frontend',
      readTime: '11 min read',
      date: 'Dec 02, 2023',
      likes: 432,
      comments: 54,
    },
  ]);

  // ---- 热门标签榜单（Trending 页面用） ----
  await store.seed('trending_tags', [
    { name: 'AI & ML', count: '2.4k articles', trend: '+34%' },
    { name: 'Rust', count: '1.8k articles', trend: '+28%' },
    { name: 'Edge Computing', count: '1.2k articles', trend: '+22%' },
    { name: 'WebAssembly', count: '980 articles', trend: '+18%' },
    { name: 'Accessibility', count: '870 articles', trend: '+15%' },
    { name: 'TypeScript 5.0', count: '760 articles', trend: '+12%' },
    { name: 'Serverless', count: '650 articles', trend: '+10%' },
    { name: 'Design Systems', count: '540 articles', trend: '+8%' },
  ]);

  // ---- 推荐作者（首页/Trending 页面展示） ----
  await store.seed('featured_authors', [
    {
      name: 'Alex Chen',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
      role: 'Senior Frontend Engineer',
      articles: 48,
      followers: '12.5k',
      slug: 'alex-chen',
    },
    {
      name: 'Sarah Miller',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
      role: 'Product Designer',
      articles: 32,
      followers: '8.9k',
      slug: 'sarah-miller',
    },
    {
      name: 'David Park',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
      role: 'Backend Engineer',
      articles: 15,
      followers: '1.8k',
      slug: 'david-park',
    },
  ]);

  // ---- 关于页数据：核心指标 ----
  await store.seed('about_stats', [
    { value: '50K+', label: 'Active Readers' },
    { value: '2,000+', label: 'Published Articles' },
    { value: '500+', label: 'Expert Writers' },
    { value: '100+', label: 'Countries Reached' },
  ]);
  // 关于页数据：价值观
  await store.seed('about_values', [
    {
      title: 'Quality First',
      description:
        'We believe in publishing well-researched, in-depth content that provides real value.',
    },
    {
      title: 'Community Driven',
      description: 'Our platform thrives on diverse perspectives from our global community.',
    },
    {
      title: 'Innovation',
      description: 'We stay ahead of the curve, covering emerging technologies and trends.',
    },
    {
      title: 'Inclusivity',
      description: 'We welcome voices from all backgrounds and make tech knowledge accessible.',
    },
  ]);
  // 关于页数据：团队成员
  await store.seed('about_team', [
    {
      name: 'Alex Chen',
      role: 'Founder & CEO',
      bio: 'Former Google engineer with a passion for knowledge sharing',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    },
    {
      name: 'Sarah Miller',
      role: 'Head of Content',
      bio: 'Award-winning writer with 10+ years in tech journalism',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    },
    {
      name: 'David Park',
      role: 'Lead Developer',
      bio: 'Full-stack developer and open-source enthusiast',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    },
    {
      name: 'Emily Watson',
      role: 'Community Manager',
      bio: 'Building bridges between writers and readers worldwide',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    },
  ]);

  // ---- 分类详情页文章列表 ----
  await store.seed('category_articles', [
    {
      id: ARTICLE_IDS.rsc,
      title: 'Mastering React Server Components in 2024',
      excerpt: 'A deep dive into how Server Components change the paradigm...',
      image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=250&fit=crop',
      tag: 'Engineering',
      tagClass: 'tag-engineering',
      readTime: '8 min read',
      date: 'Nov 12, 2023',
      likes: 342,
      comments: 56,
      author: {
        name: 'Alex Chen',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
      },
      featured: true,
    },
    {
      id: ARTICLE_IDS.color,
      title: 'The Psychology of Colors in Digital Products',
      excerpt: 'Understanding how different hues impact user behavior...',
      image: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=400&h=250&fit=crop',
      tag: 'Design',
      tagClass: 'tag-design',
      readTime: '6 min read',
      date: 'Nov 08, 2023',
      likes: 218,
      comments: 24,
      author: {
        name: 'Sarah Miller',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      },
      featured: false,
    },
    {
      id: ARTICLE_IDS.graphql,
      title: 'Building Resilient APIs with GraphQL',
      excerpt: 'Best practices for designing, implementing, and securing GraphQL endpoints...',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=250&fit=crop',
      tag: 'Architecture',
      tagClass: 'tag-architecture',
      readTime: '10 min read',
      date: 'Oct 30, 2023',
      likes: 189,
      comments: 42,
      author: {
        name: 'David Park',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      },
      featured: false,
    },
    {
      id: ARTICLE_IDS.ts5,
      title: "TypeScript 5.0: What's New and Exciting",
      excerpt: 'Exploring the latest features in TypeScript 5.0...',
      image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=250&fit=crop',
      tag: 'Engineering',
      tagClass: 'tag-engineering',
      readTime: '7 min read',
      date: 'Oct 25, 2023',
      likes: 156,
      comments: 31,
      author: {
        name: 'Emily Watson',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      },
      featured: false,
    },
    {
      id: ARTICLE_IDS.cssGrid,
      title: 'CSS Grid vs Flexbox: When to Use Which',
      excerpt: 'A comprehensive comparison of CSS Grid and Flexbox...',
      image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=400&h=250&fit=crop',
      tag: 'Frontend',
      tagClass: 'tag-frontend',
      readTime: '5 min read',
      date: 'Oct 20, 2023',
      likes: 423,
      comments: 67,
      author: {
        name: 'Michael Brown',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
      },
      featured: true,
    },
    {
      id: ARTICLE_IDS.microservices,
      title: 'Microservices Communication Patterns',
      excerpt: 'Understanding synchronous vs asynchronous communication...',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=250&fit=crop',
      tag: 'Architecture',
      tagClass: 'tag-architecture',
      readTime: '12 min read',
      date: 'Oct 15, 2023',
      likes: 278,
      comments: 45,
      author: {
        name: 'Lisa Zhang',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
      },
      featured: false,
    },
  ]);

  // ---- 分类详情页热门作者 ----
  await store.seed('category_top_authors', [
    {
      name: 'Alex Chen',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
      role: 'Senior Engineer',
      articles: 12,
      followers: '3.2k',
      verified: true,
    },
    {
      name: 'Sarah Miller',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
      role: 'Product Designer',
      articles: 8,
      followers: '2.1k',
      verified: true,
    },
    {
      name: 'David Park',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
      role: 'Architect',
      articles: 6,
      followers: '1.8k',
      verified: false,
    },
    {
      name: 'Emily Watson',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      role: 'Full Stack Dev',
      articles: 15,
      followers: '4.5k',
      verified: true,
    },
  ]);

  // ---- 学习路径（3 档难度） ----
  await store.seed('learning_paths', [
    {
      title: 'Getting Started',
      description: 'Perfect for beginners',
      steps: 5,
      duration: '2 weeks',
      level: 'Beginner',
    },
    {
      title: 'Advanced Techniques',
      description: 'Level up your skills',
      steps: 8,
      duration: '1 month',
      level: 'Advanced',
    },
    {
      title: 'Expert Mastery',
      description: 'Become an expert',
      steps: 12,
      duration: '2 months',
      level: 'Expert',
    },
  ]);

  // ---- 标签贡献者榜单 ----
  await store.seed('tag_contributors', [
    {
      name: 'Alex Chen',
      articles: 12,
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    },
    {
      name: 'Sarah Miller',
      articles: 8,
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    },
    {
      name: 'David Park',
      articles: 6,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    },
    {
      name: 'Emily Watson',
      articles: 15,
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    },
  ]);

  // ---- 邮件订阅列表（初始为空） ----
  await store.seed('newsletter', []);

  console.log('✅ Seed data initialized');
}
